services:
  search-l3s-gateway:
    # image: ghcr.io/e-learning-by-sse/search-l3s_gateway-service:latest
    build: .
    restart: always
    ports:
      - "9040:9040"
    volumes:
      - .:/code
    environment:
      # POSTGRES_HOST: l3s-search-db
      PYTHONUNBUFFERED: 1
      environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
      FLASK_RUN_PORT: 9040

      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "SearchDB"
      POSTGRES_PORT: "5432"
      POSTGRES_HOST: "l3s-search-db"

      L3S_GATEWAY_HOST_NAME: "localhost"
      L3S_GATEWAY_PORT: 9040
      L3S_AIMETA_PORT: 9041
      L3S_RECSYS_PORT: 9042
      L3S_SEARCH_PORT: 9043
      L3S_AIMETA_HOST: "https://staging.sse.uni-hildesheim.de:9041/l3s-aimeta/"
      L3S_RECSYS_HOST: "https://staging.sse.uni-hildesheim.de:9042/l3s-recsys/"
      L3S_SEARCH_HOST: "https://staging.sse.uni-hildesheim.de:9043/l3s-search/"
      SSE_SEARCH_HOST: "https://staging.sse.uni-hildesheim.de:9011"

      MLS_BASE_URL: "https://search.mls2.de"
      MLS_LOGIN_SERVER_URL: "https://develop-login.mls2.de"
      MLS_REALM: "nws"
      MLS_CLIENT_ID: "mls2-search"
      MLS_CLIENT_SECRET: "S6P8W0BpM3i69TFfzwO5Gr5fUsYfvYyS"
      MLS_USERNAME: "SEARCH"
      MLS_USER_PASSWORD: "'V269: z,zW5D"
      MLS_GRANT_TYPE: "password"

      OPENAI_API_KEY: "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"
    depends_on:
      - l3s-search-db
    networks:
      - search
    
  l3s-search-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: SearchDB
      POSTGRES_PORT: "5432"
    ports:
      - 5432:5432
    volumes:
      - l3s-db-vol:/var/lib/postgresql/data/
    networks:
      - search

networks:
  search:

volumes:
  l3s-db-vol: