services:
  search_l3s_gateway:
    container_name: search_l3s_gateway
    image: search_l3s_gateway:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@l3s-db:5435/postgres
    depends_on:
      - l3s-db
    networks:
      - search
  dev-db-l3s:
    image: postgres:13
    # ports:
    #   - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: l3s-db
    networks:
      - search
networks:
  search: