# coding: utf-8

"""
    L3S AI-Meta Service(AIMS) for SEARCH

    Welcome to the Swagger UI documentation site!  # noqa: E501

    OpenAPI spec version: 0.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DtoTitleResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'results': 'AllOfDtoTitleResponseResults'
    }

    attribute_map = {
        'message': 'message',
        'results': 'results'
    }

    def __init__(self, message=None, results=None):  # noqa: E501
        """DtoTitleResponse - a model defined in Swagger"""  # noqa: E501
        self._message = None
        self._results = None
        self.discriminator = None
        self.message = message
        if results is not None:
            self.results = results

    @property
    def message(self):
        """Gets the message of this DtoTitleResponse.  # noqa: E501

        Success message  # noqa: E501

        :return: The message of this DtoTitleResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this DtoTitleResponse.

        Success message  # noqa: E501

        :param message: The message of this DtoTitleResponse.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def results(self):
        """Gets the results of this DtoTitleResponse.  # noqa: E501

        Results  # noqa: E501

        :return: The results of this DtoTitleResponse.  # noqa: E501
        :rtype: AllOfDtoTitleResponseResults
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this DtoTitleResponse.

        Results  # noqa: E501

        :param results: The results of this DtoTitleResponse.  # noqa: E501
        :type: AllOfDtoTitleResponseResults
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DtoTitleResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DtoTitleResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
