# coding: utf-8

"""
    MLS2 API

    Central API  # noqa: E501

    OpenAPI spec version: 0.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChangelogJsonld(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context': 'OneOfChangelogJsonldContext',
        'id': 'str',
        'type': 'str',
        'id': 'int',
        'version': 'str',
        'type': 'str',
        'text': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime'
    }

    attribute_map = {
        'context': '@context',
        'id': '@id',
        'type': '@type',
        'id': 'id',
        'version': 'version',
        'type': 'type',
        'text': 'text',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt'
    }

    def __init__(self, context=None, id=None, type=None, id=None, version=None, type=None, text=None, created_at=None, updated_at=None):  # noqa: E501
        """ChangelogJsonld - a model defined in Swagger"""  # noqa: E501
        self._context = None
        self._id = None
        self._type = None
        self._id = None
        self._version = None
        self._type = None
        self._text = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        if context is not None:
            self.context = context
        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if id is not None:
            self.id = id
        if version is not None:
            self.version = version
        if type is not None:
            self.type = type
        if text is not None:
            self.text = text
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def context(self):
        """Gets the context of this ChangelogJsonld.  # noqa: E501


        :return: The context of this ChangelogJsonld.  # noqa: E501
        :rtype: OneOfChangelogJsonldContext
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this ChangelogJsonld.


        :param context: The context of this ChangelogJsonld.  # noqa: E501
        :type: OneOfChangelogJsonldContext
        """

        self._context = context

    @property
    def id(self):
        """Gets the id of this ChangelogJsonld.  # noqa: E501


        :return: The id of this ChangelogJsonld.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChangelogJsonld.


        :param id: The id of this ChangelogJsonld.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this ChangelogJsonld.  # noqa: E501


        :return: The type of this ChangelogJsonld.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ChangelogJsonld.


        :param type: The type of this ChangelogJsonld.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def id(self):
        """Gets the id of this ChangelogJsonld.  # noqa: E501


        :return: The id of this ChangelogJsonld.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChangelogJsonld.


        :param id: The id of this ChangelogJsonld.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def version(self):
        """Gets the version of this ChangelogJsonld.  # noqa: E501


        :return: The version of this ChangelogJsonld.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ChangelogJsonld.


        :param version: The version of this ChangelogJsonld.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def type(self):
        """Gets the type of this ChangelogJsonld.  # noqa: E501


        :return: The type of this ChangelogJsonld.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ChangelogJsonld.


        :param type: The type of this ChangelogJsonld.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def text(self):
        """Gets the text of this ChangelogJsonld.  # noqa: E501


        :return: The text of this ChangelogJsonld.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ChangelogJsonld.


        :param text: The text of this ChangelogJsonld.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def created_at(self):
        """Gets the created_at of this ChangelogJsonld.  # noqa: E501


        :return: The created_at of this ChangelogJsonld.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ChangelogJsonld.


        :param created_at: The created_at of this ChangelogJsonld.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this ChangelogJsonld.  # noqa: E501


        :return: The updated_at of this ChangelogJsonld.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ChangelogJsonld.


        :param updated_at: The updated_at of this ChangelogJsonld.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChangelogJsonld, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChangelogJsonld):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
