# coding: utf-8

"""
    MLS2 API

    Central API  # noqa: E501

    OpenAPI spec version: 0.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ChatMessageChatMessageItemRead(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'content': 'str',
        'sender': 'str',
        'type': 'str',
        'chat': 'str'
    }

    attribute_map = {
        'id': 'id',
        'content': 'content',
        'sender': 'sender',
        'type': 'type',
        'chat': 'chat'
    }

    def __init__(self, id=None, content=None, sender=None, type=None, chat=None):  # noqa: E501
        """ChatMessageChatMessageItemRead - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._content = None
        self._sender = None
        self._type = None
        self._chat = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if content is not None:
            self.content = content
        if sender is not None:
            self.sender = sender
        if type is not None:
            self.type = type
        if chat is not None:
            self.chat = chat

    @property
    def id(self):
        """Gets the id of this ChatMessageChatMessageItemRead.  # noqa: E501


        :return: The id of this ChatMessageChatMessageItemRead.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChatMessageChatMessageItemRead.


        :param id: The id of this ChatMessageChatMessageItemRead.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def content(self):
        """Gets the content of this ChatMessageChatMessageItemRead.  # noqa: E501


        :return: The content of this ChatMessageChatMessageItemRead.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ChatMessageChatMessageItemRead.


        :param content: The content of this ChatMessageChatMessageItemRead.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def sender(self):
        """Gets the sender of this ChatMessageChatMessageItemRead.  # noqa: E501


        :return: The sender of this ChatMessageChatMessageItemRead.  # noqa: E501
        :rtype: str
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this ChatMessageChatMessageItemRead.


        :param sender: The sender of this ChatMessageChatMessageItemRead.  # noqa: E501
        :type: str
        """

        self._sender = sender

    @property
    def type(self):
        """Gets the type of this ChatMessageChatMessageItemRead.  # noqa: E501


        :return: The type of this ChatMessageChatMessageItemRead.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ChatMessageChatMessageItemRead.


        :param type: The type of this ChatMessageChatMessageItemRead.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def chat(self):
        """Gets the chat of this ChatMessageChatMessageItemRead.  # noqa: E501


        :return: The chat of this ChatMessageChatMessageItemRead.  # noqa: E501
        :rtype: str
        """
        return self._chat

    @chat.setter
    def chat(self, chat):
        """Sets the chat of this ChatMessageChatMessageItemRead.


        :param chat: The chat of this ChatMessageChatMessageItemRead.  # noqa: E501
        :type: str
        """

        self._chat = chat

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChatMessageChatMessageItemRead, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChatMessageChatMessageItemRead):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
