# coding: utf-8

"""
    MLS2 API

    Central API  # noqa: E501

    OpenAPI spec version: 0.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GroupTaskTodoGroupTaskTodoItemWrite(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'task': 'str',
        'form_answers': 'list[str]',
        'group_task_todo_links': 'list[str]',
        'status': 'str',
        'note': 'str',
        'instructors_to_notify': 'list[str]',
        'equipments': 'list[str]'
    }

    attribute_map = {
        'task': 'task',
        'form_answers': 'formAnswers',
        'group_task_todo_links': 'groupTaskTodoLinks',
        'status': 'status',
        'note': 'note',
        'instructors_to_notify': 'instructorsToNotify',
        'equipments': 'equipments'
    }

    def __init__(self, task=None, form_answers=None, group_task_todo_links=None, status=None, note=None, instructors_to_notify=None, equipments=None):  # noqa: E501
        """GroupTaskTodoGroupTaskTodoItemWrite - a model defined in Swagger"""  # noqa: E501
        self._task = None
        self._form_answers = None
        self._group_task_todo_links = None
        self._status = None
        self._note = None
        self._instructors_to_notify = None
        self._equipments = None
        self.discriminator = None
        self.task = task
        if form_answers is not None:
            self.form_answers = form_answers
        if group_task_todo_links is not None:
            self.group_task_todo_links = group_task_todo_links
        if status is not None:
            self.status = status
        if note is not None:
            self.note = note
        if instructors_to_notify is not None:
            self.instructors_to_notify = instructors_to_notify
        if equipments is not None:
            self.equipments = equipments

    @property
    def task(self):
        """Gets the task of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501


        :return: The task of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :rtype: str
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this GroupTaskTodoGroupTaskTodoItemWrite.


        :param task: The task of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :type: str
        """
        if task is None:
            raise ValueError("Invalid value for `task`, must not be `None`")  # noqa: E501

        self._task = task

    @property
    def form_answers(self):
        """Gets the form_answers of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501


        :return: The form_answers of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :rtype: list[str]
        """
        return self._form_answers

    @form_answers.setter
    def form_answers(self, form_answers):
        """Sets the form_answers of this GroupTaskTodoGroupTaskTodoItemWrite.


        :param form_answers: The form_answers of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :type: list[str]
        """

        self._form_answers = form_answers

    @property
    def group_task_todo_links(self):
        """Gets the group_task_todo_links of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501


        :return: The group_task_todo_links of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :rtype: list[str]
        """
        return self._group_task_todo_links

    @group_task_todo_links.setter
    def group_task_todo_links(self, group_task_todo_links):
        """Sets the group_task_todo_links of this GroupTaskTodoGroupTaskTodoItemWrite.


        :param group_task_todo_links: The group_task_todo_links of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :type: list[str]
        """

        self._group_task_todo_links = group_task_todo_links

    @property
    def status(self):
        """Gets the status of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501


        :return: The status of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this GroupTaskTodoGroupTaskTodoItemWrite.


        :param status: The status of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def note(self):
        """Gets the note of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501


        :return: The note of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this GroupTaskTodoGroupTaskTodoItemWrite.


        :param note: The note of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :type: str
        """

        self._note = note

    @property
    def instructors_to_notify(self):
        """Gets the instructors_to_notify of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501


        :return: The instructors_to_notify of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :rtype: list[str]
        """
        return self._instructors_to_notify

    @instructors_to_notify.setter
    def instructors_to_notify(self, instructors_to_notify):
        """Sets the instructors_to_notify of this GroupTaskTodoGroupTaskTodoItemWrite.


        :param instructors_to_notify: The instructors_to_notify of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :type: list[str]
        """

        self._instructors_to_notify = instructors_to_notify

    @property
    def equipments(self):
        """Gets the equipments of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501


        :return: The equipments of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :rtype: list[str]
        """
        return self._equipments

    @equipments.setter
    def equipments(self, equipments):
        """Sets the equipments of this GroupTaskTodoGroupTaskTodoItemWrite.


        :param equipments: The equipments of this GroupTaskTodoGroupTaskTodoItemWrite.  # noqa: E501
        :type: list[str]
        """

        self._equipments = equipments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupTaskTodoGroupTaskTodoItemWrite, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupTaskTodoGroupTaskTodoItemWrite):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
