# coding: utf-8

"""
    MLS2 API

    Central API  # noqa: E501

    OpenAPI spec version: 0.7.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaskTodoFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'task_todo': 'str',
        'question_uuid': 'str',
        'file_index': 'int',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'id': 'int',
        'custom_filename': 'str',
        'file_resource': 'str'
    }

    attribute_map = {
        'task_todo': 'taskTodo',
        'question_uuid': 'questionUUID',
        'file_index': 'fileIndex',
        'created_at': 'createdAt',
        'updated_at': 'updatedAt',
        'id': 'id',
        'custom_filename': 'customFilename',
        'file_resource': 'fileResource'
    }

    def __init__(self, task_todo=None, question_uuid=None, file_index=None, created_at=None, updated_at=None, id=None, custom_filename=None, file_resource=None):  # noqa: E501
        """TaskTodoFile - a model defined in Swagger"""  # noqa: E501
        self._task_todo = None
        self._question_uuid = None
        self._file_index = None
        self._created_at = None
        self._updated_at = None
        self._id = None
        self._custom_filename = None
        self._file_resource = None
        self.discriminator = None
        if task_todo is not None:
            self.task_todo = task_todo
        if question_uuid is not None:
            self.question_uuid = question_uuid
        if file_index is not None:
            self.file_index = file_index
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at
        if id is not None:
            self.id = id
        if custom_filename is not None:
            self.custom_filename = custom_filename
        if file_resource is not None:
            self.file_resource = file_resource

    @property
    def task_todo(self):
        """Gets the task_todo of this TaskTodoFile.  # noqa: E501


        :return: The task_todo of this TaskTodoFile.  # noqa: E501
        :rtype: str
        """
        return self._task_todo

    @task_todo.setter
    def task_todo(self, task_todo):
        """Sets the task_todo of this TaskTodoFile.


        :param task_todo: The task_todo of this TaskTodoFile.  # noqa: E501
        :type: str
        """

        self._task_todo = task_todo

    @property
    def question_uuid(self):
        """Gets the question_uuid of this TaskTodoFile.  # noqa: E501


        :return: The question_uuid of this TaskTodoFile.  # noqa: E501
        :rtype: str
        """
        return self._question_uuid

    @question_uuid.setter
    def question_uuid(self, question_uuid):
        """Sets the question_uuid of this TaskTodoFile.


        :param question_uuid: The question_uuid of this TaskTodoFile.  # noqa: E501
        :type: str
        """

        self._question_uuid = question_uuid

    @property
    def file_index(self):
        """Gets the file_index of this TaskTodoFile.  # noqa: E501


        :return: The file_index of this TaskTodoFile.  # noqa: E501
        :rtype: int
        """
        return self._file_index

    @file_index.setter
    def file_index(self, file_index):
        """Sets the file_index of this TaskTodoFile.


        :param file_index: The file_index of this TaskTodoFile.  # noqa: E501
        :type: int
        """

        self._file_index = file_index

    @property
    def created_at(self):
        """Gets the created_at of this TaskTodoFile.  # noqa: E501


        :return: The created_at of this TaskTodoFile.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this TaskTodoFile.


        :param created_at: The created_at of this TaskTodoFile.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this TaskTodoFile.  # noqa: E501


        :return: The updated_at of this TaskTodoFile.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this TaskTodoFile.


        :param updated_at: The updated_at of this TaskTodoFile.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this TaskTodoFile.  # noqa: E501


        :return: The id of this TaskTodoFile.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TaskTodoFile.


        :param id: The id of this TaskTodoFile.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def custom_filename(self):
        """Gets the custom_filename of this TaskTodoFile.  # noqa: E501


        :return: The custom_filename of this TaskTodoFile.  # noqa: E501
        :rtype: str
        """
        return self._custom_filename

    @custom_filename.setter
    def custom_filename(self, custom_filename):
        """Sets the custom_filename of this TaskTodoFile.


        :param custom_filename: The custom_filename of this TaskTodoFile.  # noqa: E501
        :type: str
        """

        self._custom_filename = custom_filename

    @property
    def file_resource(self):
        """Gets the file_resource of this TaskTodoFile.  # noqa: E501


        :return: The file_resource of this TaskTodoFile.  # noqa: E501
        :rtype: str
        """
        return self._file_resource

    @file_resource.setter
    def file_resource(self, file_resource):
        """Sets the file_resource of this TaskTodoFile.


        :param file_resource: The file_resource of this TaskTodoFile.  # noqa: E501
        :type: str
        """

        self._file_resource = file_resource

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskTodoFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskTodoFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
