"""empty message

Revision ID: 685c836d2582
Revises: 2b0b4c8bd79e
Create Date: 2023-10-18 15:58:00.060458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685c836d2582'
down_revision = '2b0b4c8bd79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('another_id', sa.String(length=256), server_default=sa.text('lambda: str(uuid4())'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('another_id')

    # ### end Alembic commands ###
