"""empty message

Revision ID: 73d024849942
Revises: a1401294d868
Create Date: 2023-10-18 15:37:38.547896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d024849942'
down_revision = 'a1401294d868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.VARCHAR(length=256), server_default=sa.text("'<function Test.<lambda> at 0x7f261a556160>'::character varying"), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
