"""empty message

Revision ID: 7a96aea4870b
Revises: 94e2015516da
Create Date: 2023-10-18 14:19:33.427122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a96aea4870b'
down_revision = '94e2015516da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id_3', sa.String(length=36), server_default='lambda: str(uuid4())', nullable=True))
        batch_op.create_unique_constraint(None, ['public_id_3'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('public_id_3')

    # ### end Alembic commands ###
